# Generated by Django 3.2.5 on 2021-07-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceroomuser',
            name='leave_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
